language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install ubuntu-sdk
script: make
