language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-add-repository -y ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get install -qq qtbase5-dev qtbase5-dev-tools libqt5widgets5
script: make
